[
    {
        "ref": 89512,
        "image": "https://static.wixstatic.com/media/b18b06_8aa71452f01b44479fc9b834267dfb2c~mv2.jpg/v1/fill/w_420,h_420,al_c,q_85,usm_0.66_1.00_0.01/b18b06_8aa71452f01b44479fc9b834267dfb2c~mv2.webp",
        "name_product": "Mon rouge - Eau de Parfum 50ml",
        "price": "120,000 TND Prix",
        "date": "December 2019",
          "name_category": "parfums",
        "description": "Un sillage affirmé et rayonnant mêlant la puissance du Patchouli, l’éclat de l’Essence de Néroli et la sensualité de l’Iris."
    },
    {
        "ref": 2522,
        "image": "https://static.wixstatic.com/media/587acd_fb8874cc35dd4aa99717ff62305bced1~mv2.png/v1/fill/w_420,h_420,al_c,q_90,usm_0.66_1.00_0.01/587acd_fb8874cc35dd4aa99717ff62305bced1~mv2.webp",
        "name_product": "Eau de Toilette Bois de Sauge - 100 ml",
        "price": "130,000 TND Prix",
        "date": "october 2019",
           "name_category": "parfums",
        "description": "L'intensité d'une fraîcheur aromatique"
    },
    {
        "ref": 9065,
        "image": "https://static.wixstatic.com/media/b18b06_1ce0bc95547f4481a244b30467c7a8f1~mv2.png/v1/fill/w_420,h_420,al_c,q_90,usm_0.66_1.00_0.01/b18b06_1ce0bc95547f4481a244b30467c7a8f1~mv2.webp",
        "name_product": "Fond de Teint Super Mat Beige 200 Tube 30ML",
        "price": "40,000 TND Prix",
        "date": "october 2019",
        "name_category": "maquillage",
        "description": "Le Fond de Teint Super Mat unifie et masque les imperfections avec une haute pigmentation pour une couvrance modulable (moyenne à élevée) et une tenue toute la journée La peau est matifiée grâce à la poudre de thé Boréal et rééquilibrée : jour après jour, les zones de brillances sont atténuées. Sur la peau la texture crémeuse et fluide fusionne avec la peau pour un confort assuré grâce à notre nouvelle formule composée à 86% de base soin. Son +: Tenue 16h* Texture crème non grasse- Non comédogène, non occlusif. Extrait végétal de poudre de Thé Boréal 100% d'origine végétale."
    },
    {
        "ref":4602,
        "image": "https://static.wixstatic.com/media/19572a_e1636a00f73847ec9bc6c9153cb902ea~mv2.png/v1/fill/w_420,h_420,al_c,q_90,usm_0.66_1.00_0.01/19572a_e1636a00f73847ec9bc6c9153cb902ea~mv2.webp",
        "name_product": "Mascara Intense Metamorphose Waterproof - Noir",
        "price": "57,000 TND Prix",
        "date": "september 2019",
        "name_category": "maquillage",
        "description": "Intense Métamorphose Waterproof, comme sa version standard, ne fait aucun compromis, des cils visiblement plus volumineux, recourbés et allongés. Grâce à sa brosse fibre en forme de sablier, intuitive, douce et facile d'utilisation, chaque cil est étoffé, gainé, allongé, du coin interne ou coin externe de l’œil, aucun d’eux n’est oublié.Sa formule est enrichie en Huile de Ricin nourrissante et en eau de Bleuet doux pour les yeux les plus sensibles et porteurs de lentilles."
    },
    {
        "ref": 90012,
        "image": "https://static.wixstatic.com/media/dcd155_eb81341083894aba8f000e49eb3a8076~mv2.png/v1/fill/w_420,h_420,al_c,q_90,usm_0.66_1.00_0.01/dcd155_eb81341083894aba8f000e49eb3a8076~mv2.webp",
        "name_product": "Grand Rouge Mat - 3.7 gr",
        "price": "47,000 TND Prix",
        "date": "september 2017",
        "name_category": "maquillage",
        "description": "Ultra mat - ultra confort"
    },
    {
        "ref": 85108,
        "image": "https://static.wixstatic.com/media/b18b06_922957b9c1ff424e8d6619a37a271611~mv2.webp",
        "name_product": "Lait Corps Réparateur Karité Merveilleux",
        "price": "27,000 TND Prix",
        "date": "mars 2020",
        "name_category": "corps et douche",
        "description": "Nos chercheurs en Cosmétique Végétale ont sélectionné le Beurre de Karité pour ses vertus réparatrices et nutritives exceptionnelles. Intensément nourrie, la peau est plus lisse et retrouve tout son confort. Ce lait-crème enveloppant s’applique quotidiennement sur l’ensemble du corps et pénètre instantanément."
    },
    {
        "ref": 5574,
      "image": "https://static.wixstatic.com/media/b18b06_f8491dbf3aa2437abb6d011285971b6c~mv2.webp",
        "name_product": "Bain Douche Baies Délicieuses",
        "price": "20,000 TND Prix",
        "date": "mars 2020",
        "name_category": "corps et douche",
        "description": "Sous la douche, un parfum énergisant et pétillant évoquant les Baies de Canneberge. Avec sa base lavante d'origine végétale sans sulfates* et au pH neutre pour la peau, ce gel douche fabriqué en France nettoie la peau en douceur et la laisse délicatement parfumée.Succombez aux délices fruités des baies de Noël. Une senteur pétillante et joyeuse, déclinée dans toute une collection de Noël en édition limitée."
    },
    {
        "ref": 7432,
      "image": "https://static.wixstatic.com/media/b18b06_0bc2173c26904e29a8832b8b4b8d7183~mv2.png/v1/fill/w_420,h_420,al_c,q_90,usm_0.66_1.00_0.01/b18b06_0bc2173c26904e29a8832b8b4b8d7183~mv2.webp",
        "name_product": "Huile Sèche Précieuse Monoi-100 ML",
        "price": "49,000 TND Prix",
        "date": "mars 2020",
        "name_category": "corps et douche",
        "description": "Ultra mat - ultra confort"
    },
    {
        "ref": 40022,
        "image": "https://static.wixstatic.com/media/dcd155_704a1818400d4a4ebaf414e8b902da6f~mv2.png/v1/fill/w_420,h_420,al_c,q_90,usm_0.66_1.00_0.01/dcd155_704a1818400d4a4ebaf414e8b902da6f~mv2.webp",
        "name_product": "Laque Effet Gel Rose Vif - 5 ml",
        "price": "19,000 TND Prix",
        "date": "september 2018",
        "name_category": "maquillage",
        "description": "Toute la beauté & la tenue du gel chez vous !"
    },
    {
        "ref": 7692,
        "image": "https://static.wixstatic.com/media/19572a_e4a23a8aa5664e14a3977e0855bb54c4~mv2.jpg/v1/fill/w_420,h_420,al_c,q_85,usm_0.66_1.00_0.01/19572a_e4a23a8aa5664e14a3977e0855bb54c4~mv2.webp",
        "name_product": "Soin Anti-Pollution Réparateur Jour",
        "price": "86,000 TND Prix",
        "date": "mars 2020",
        "name_category": "corps et douche",
        "description": "Le Soin Anti-Pollution Réparateur Jour désasphyxie immédiatement la peau, elle est protégée face aux méfaits de la pollution responsables du vieillissement prématuré de la peau. Dès 1 mois, rides et ridules sont réduites ; la peau est réparée, fortifiée et paraît éclatante de santé Dans notre élixir botanique, la Micro-Algue et la Capucine de Bretagne stimulent l'oxygénation et la détoxification des cellules de la peau (1). Actifs issus de filières locales respectueuses de la biodiversité."
    },
    {
        "ref": 882,
        "image": "https://static.wixstatic.com/media/dcd155_17665ad2332f4f3e9c676e56b2035c86~mv2.png/v1/fill/w_420,h_420,al_c,q_90,usm_0.66_1.00_0.01/dcd155_17665ad2332f4f3e9c676e56b2035c86~mv2.webp",
        "name_product": "Blush Couleur Végétale - 4.0 gr",
        "price": "20,400 TND Prix",
        "date": "juin 2020",
        "name_category": "maquillage",
        "description": "Rehaussez vos joues et votre look !"
    },
    {
        "ref": 142,
        "image": "https://static.wixstatic.com/media/b18b06_9c8479d99de54df88d29f0c4df47a148~mv2.jpg/v1/fill/w_420,h_420,al_c,q_85,usm_0.66_1.00_0.01/b18b06_9c8479d99de54df88d29f0c4df47a148~mv2.webp",
        "name_product": "Le Gel Nettoyant Ultra-Fraîcheur Pure Algue - 125ml",
        "price": "22,000 TND Prix",
        "date": "juin 2020",
        "name_category": "soin visage",
        "description": "Nettoie, oxygène et rafraîchit parfaitement la peau "
    },
    {
        "ref": 27782,
        "image": "https://static.wixstatic.com/media/b18b06_e66cbe86035b4ab99797099bc017b9aa~mv2.webp",
        "name_product": "FILLER VEGETAL Soin Anti-Rides Repulpant JOUR",
        "price": "67,000 TND Prix",
        "date": "juin 2018",
        "name_category": "soin visage",
        "description": "Immédiatement, la peau est hydratée, lissée et repulpée. Jour après jour, elle paraît raffermie.Après 6 semaines, les rides mêmes marquées sont réduites."
    }
]